apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  # How many copies of each pod do we want?
  replicas: 3
 
  selector:
    matchLabels:
      # This must match the labels we set on the pod!
      app: front-app
 
  # This template field is a regular pod configuration
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: front-app
    spec:
      containers:
        - name: front-app
          image: front-app
          ports:
            - containerPort: 9000
          env:
            - name: ENVIRONMENT
              value: "DEV"
            - name: HOST
              value: "localhost"
            - name: PORT
              value: "9000"
            - name: REDIS_HOST
              value:  "0.0.0.0"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"